{
  "version": 2,
  "snapshot": {
    "widths": [375, 768, 1024, 1440],
    "minHeight": 1024,
    "percyCSS": ".percy-hide { visibility: hidden !important; }"
  },
  "discovery": {
    "allowedHostnames": ["localhost", "internetfriends.xyz", "octopus.do"],
    "networkIdleTimeout": 750
  },
  "static": {
    "baseUrl": "http://localhost:3000",
    "include": [
      "/",
      "/design-system",
      "/orchestrator", 
      "/visual-comparison",
      "/theme-demo",
      "/curriculum",
      "/contact"
    ]
  }
}