name: OpenCode Orchestration CI

on:
  push:
    branches: [ main, epic/glass-refinement-v1 ]
  pull_request:
    branches: [ main ]

jobs:
  orchestration-validation:
    name: Validate OpenCode Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      working-directory: ./components
      
    - name: Type checking
      run: bun run typecheck
      working-directory: ./components
      
    - name: Validate state diagrams
      run: bun run scan:diagrams
      working-directory: ./components
      
    - name: Run helper scoring tests
      run: bun run test
      working-directory: ./components
      
    - name: Generate delegation plan
      run: bun run delegate:opencode > delegation-plan.json
      working-directory: ./components
      
    - name: Upload delegation plan artifact
      uses: actions/upload-artifact@v3
      with:
        name: opencode-delegation-plan
        path: ./components/delegation-plan.json
        retention-days: 7
        
    - name: Component analysis validation
      run: bun run validate:helper --limit=3 --json > component-analysis.json
      working-directory: ./components
      
    - name: Upload component analysis
      uses: actions/upload-artifact@v3  
      with:
        name: component-analysis-report
        path: ./components/component-analysis.json
        retention-days: 7

  opencode-integration:
    name: OpenCode Integration Check
    runs-on: ubuntu-latest
    needs: orchestration-validation
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun runtime  
      uses: oven-sh/setup-bun@v1
      
    - name: Download delegation plan
      uses: actions/download-artifact@v3
      with:
        name: opencode-delegation-plan
        path: ./artifacts
        
    - name: Comment PR with delegation plan
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const plan = JSON.parse(fs.readFileSync('./artifacts/delegation-plan.json', 'utf8'));
          
          const comment = `## 🎭 OpenCode Delegation Plan
          
          **Focus**: ${plan.focus}
          **Ready Tasks**: ${plan.summary.ready}/${plan.summary.counts.analysis + plan.summary.counts.refactor + plan.summary.counts.docs + plan.summary.counts.test + plan.summary.counts.validation}
          
          ### Task Breakdown
          ${Object.entries(plan.summary.counts).map(([category, count]) => `- **${category}**: ${count} tasks`).join('\n')}
          
          <details>
          <summary>View Full Plan</summary>
          
          \`\`\`json
          ${JSON.stringify(plan, null, 2)}
          \`\`\`
          </details>
          
          Generated by orchestration workflow at ${new Date().toISOString()}`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
